import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { AllTools } from "@larksuiteoapi/lark-mcp/dist/mcp-tool/tools/index.js";
import { presetTools } from "@larksuiteoapi/lark-mcp/dist/mcp-tool/constants.js";

const require = createRequire(import.meta.url);
const root = dirname(require.resolve("@larksuiteoapi/lark-mcp/package.json"));
const version = JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version;
if (version !== "0.5.1") throw new Error("Audit the catalog extractor before upgrading lark-mcp");
const user = [
  ...new Set([...presetTools["preset.default"], ...presetTools["preset.calendar.default"]]),
];
const bot = [
  "im.v1.message.create",
  "im.v1.message.list",
  "im.v1.chat.create",
  "im.v1.chat.list",
  "contact.v3.user.batchGetId",
];
const selected = AllTools.filter((tool) => user.includes(tool.name) || bot.includes(tool.name));
const blocks = new Map();
const directory = join(root, "dist/mcp-tool/tools/en/gen-tools/zod");
// Pinned upstream emits standalone object assignments. Fail closed when its format changes.
for (const file of readdirSync(directory).filter((name) => name.endsWith(".js"))) {
  const source = readFileSync(join(directory, file), "utf8");
  for (const match of source.matchAll(/^exports\.(\w+) = (\{[\s\S]*?^\});$/gm)) {
    const name = source
      .slice(match.index, match.index + match[0].length)
      .match(/name: '([^']+)'/)?.[1];
    if (name) blocks.set(name, match[2].replaceAll("zod_1.z", "z"));
  }
}
const definitions = selected
  .filter((tool) => !tool.customHandler)
  .map((tool) => {
    const block = blocks.get(tool.name);
    if (!block || /\bexports\.|\brequire\(|\bzod_1\b/.test(block))
      throw new Error(`Cannot extract ${tool.name}`);
    return block;
  });
const builtin = selected.filter((tool) => tool.customHandler).map((tool) => tool.name);
if (JSON.stringify(builtin) !== JSON.stringify(["docx.builtin.search", "docx.builtin.import"]))
  throw new Error("Audit new custom handlers");
const output = `// Generated by scripts/generate-catalog.mjs from lark-mcp ${version}; do not edit.
// Upstream schema definitions are MIT licensed; see ../UPSTREAM_LICENSE.
import { z } from "zod";
import type { McpTool } from "@larksuiteoapi/lark-mcp/dist/mcp-tool/types/index.js";
import type { ToolName } from "@larksuiteoapi/lark-mcp/dist/mcp-tool/tools/index.js";
import { larkDocxBuiltinSearchTool, larkDocxBuiltinImportTool } from "@larksuiteoapi/lark-mcp/dist/mcp-tool/tools/en/builtin-tools/docx/builtin.js";
export const userToolNames: ToolName[] = ${JSON.stringify(user)};
export const botToolNames: ToolName[] = ${JSON.stringify(bot)};
export const selectedTools: McpTool[] = [${definitions.join(",\n")}, larkDocxBuiltinSearchTool, larkDocxBuiltinImportTool];
`;
writeFileSync(new URL("../src/catalog.generated.ts", import.meta.url), output);
writeFileSync(new URL("../UPSTREAM_LICENSE", import.meta.url), readFileSync(join(root, "LICENSE")));
execFileSync(
  "vp",
  ["fmt", fileURLToPath(new URL("../src/catalog.generated.ts", import.meta.url))],
  { stdio: "pipe" },
);
console.log(`Generated ${selected.length} definitions from ${AllTools.length} upstream tools`);
